bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

granite_tap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('about/', include('about.urls')),
    path('wishlist/', include('wishlist.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'granite_tap.views.handler404'

wishlist/urls.py
from django.urls import path
from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.wishlist, name='wishlist'),
    path('add/<int:item_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove/<int:item_id>/',
         views.remove_from_wishlist, name='remove_from_wishlist'),
]

wishlist/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}'s Wishlist"

wishlist/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from .models import Wishlist
from products.models import Product
from django.contrib import messages


def wishlist(request):
    if request.user.is_authenticated:
        wishlist_item_ids = request.session.get('wishlist', [])
        wishlist_items = Product.objects.filter(pk__in=wishlist_item_ids)

        template = 'wishlist/wishlist.html'
        context = {
            'wishlist_items': wishlist_items,

        }
        return render(request, template, context)
    else:
        return redirect('product_detail')


def add_to_wishlist(request, item_id):
    """ Add a product to the wishlist """

    product = get_object_or_404(Product, pk=item_id)

    wishlist = request.session.get('wishlist', [])

    if item_id not in wishlist:
        wishlist.append(item_id)
        messages.success(request, f'Added {product.name} to your wishlist')
    else:
        messages.info(request, f'{product.name} is already in your wishlist.')

    request.session['wishlist'] = wishlist
    return redirect('product_detail', product_id=item_id)


def remove_from_wishlist(request, item_id):
    """ Remove a product from the wishlist """
    product = get_object_or_404(Product, pk=item_id)

    wishlist = request.session.get('wishlist', [])

    if item_id in wishlist:
        wishlist.remove(item_id)
        messages.success(request, f'Removed {product.name} from your wishlist')
    else:
        messages.info(request, f'{product.name} is not in your wishlist.')

    request.session['wishlist'] = wishlist

    wishlist_url = reverse('wishlist:wishlist')
    return redirect(wishlist_url)

wishlist/templates/wishlist/wishlist.html
{% extends "base.html" %}
{% load static %}


{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col">
                <hr>
                <h2 class="logo-font mb-4">My Wishlist</h2>
                <hr>
            </div>
        </div>
        <div class="row padding100">
                {% if wishlist_items %}
                    {% for product in wishlist_items %}
                        <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                            <div class="card border-0">
                                {% if product.image %}
                                    <a href="{% url 'product_detail' product.id %}">
                                        <img class="card-img-top img-fluid custom-image" src="{{ product.image.url }}" alt="{{ product.name }}">
                                    </a>
                                {% else %}
                                    <a href="{% url 'product_detail' product.id %}">
                                        <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png"
                                            alt="{{ product.name }}">
                                    </a>
                                {% endif %}
                                <div class="card-body pb-0">
                                    <p class="mb-0">{{ product.name }}</p>
                                </div>
                                <div class="card-footer bg-white pt-0 border-0 text-left">
                                    <div class="row">
                                        <div class="col">
                                            <!-- Price -->
                                            <p class="lead mb-0 text-left font-weight-bold">£{{ product.price }}</p>
                                            <!-- ABV -->
                                            <p class="mb-0 text-left">{{ product.abv }}% ABV</p>
                                            <!-- Brewery -->
                                            {% if product.brewery %}
                                                <p class="small mt-1 mb-0 text-left">
                                                    <a href="{% url 'products' %}?brewery={{ product.brewery }}" class="dropdown-item p-0 text-muted">
                                                        <i class="fa-solid fa-beer-mug-empty"></i> {{ product.brewery }}
                                                    </a>
                                                </p>
                                            {% endif %}
                                            <!-- Category/beer type -->
                                            {% if product.category %}
                                                <p class="small mt-1 mb-0">
                                                    <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                                                        <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                                                    </a>
                                                </p>
                                            {% endif %}
                                            <!-- Rating -->
                                            {% if product.rating %}
                                                <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} /
                                                    5</small>
                                            {% else %}
                                                <small class="text-muted">No Rating</small>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <small>
                                        <a class="text-black btn btn-outline-black" href="{% url 'wishlist:remove_from_wishlist' product.id %}">
                                            Remove from Wishlist</a>
                                    </small>
                                </div>
                            </div>
                        </div>
                        {% if forloop.counter|divisibleby:1 %}
                            <div class="col-12 d-sm-none mb-5">
                                <hr>
                            </div>
                        {% endif %}
                        {% if forloop.counter|divisibleby:2 %}
                            <div class="col-12 d-none d-sm-block d-md-block d-lg-none mb-5">
                                <hr>
                            </div>
                        {% endif %}
                        {% if forloop.counter|divisibleby:3 %}
                            <div class="col-12 d-none d-lg-block d-xl-none mb-5">
                                <hr>
                            </div>
                        {% endif %}
                        {% if forloop.counter|divisibleby:4 %}
                            <div class="col-12 d-none d-xl-block mb-5">
                                <hr>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <p>Your wishlist is empty.</p>
                {% endif %}
        </div>
    </div>
{% endblock %}