bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

granite_tap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('about/', include('about.urls')),
    path('wishlist/', include('wishlist.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'granite_tap.views.handler404'

wishlist/urls.py
from django.urls import path
from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.wishlist, name='wishlist'),
    path('add/<int:item_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove/<int:item_id>/',
         views.remove_from_wishlist, name='remove_from_wishlist'),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>

    {% block meta %}
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="Discover a wide selection of local craft beers at Granite Tap. Browse our online store for unique and flavorful brews from Aberdeen and Aberdeenshire, Scotland. Shop now for a taste of the best local beers, delivered to your doorstep. Cheers to supporting local breweries!">
        <meta name="keywords" content="local beer, craft beer, online beer shop, brewery, Granite Tap, Aberdeen beer, Aberdeenshire beer, brewery near me, craft beer near me, beer gifts, gift, beer lover, beer delivery">

    {% endblock %}

    {% block extra_meta %}
    {% endblock %}

    {% block corecss %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Victor+Mono:wght@100;200;300;400;500;600;700&display=swap"
            rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link href="//cdn-images.mailchimp.com/embedcode/classic-061523.css" rel="stylesheet" type="text/css">
    {% endblock %}

    {% block extra_css %}
    {% endblock %}

    {% block corejs %}
        <script src="https://kit.fontawesome.com/7771b7a700.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
        <!-- Stripe -->
        <script src="https://js.stripe.com/v3/"></script>
        <!-- MailChimp -->
        <script type="text/javascript" src="//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js"></script>
        <script type="text/javascript">
            (function($) {
                window.fnames = new Array(); 
                window.ftypes = new Array();
                fnames[0]='EMAIL';
                ftypes[0]='email';
                fnames[1]='FNAME';
                ftypes[1]='text';
                fnames[2]='LNAME';
                ftypes[2]='text';
                fnames[3]='ADDRESS';
                ftypes[3]='address';
                fnames[4]='PHONE';
                ftypes[4]='phone';
                fnames[5]='BIRTHDAY';
                ftypes[5]='birthday';
                }(jQuery));var $mcj = jQuery.noConflict(true);
        </script>
    {% endblock %}

    {% block extra_js %}
    {% endblock %}

    <!-- Favicon link -->
    <link rel="icon" type="image/x-icon" href="{% static 'favicon_gt.png' %}">

    <title>Granite Tap {% block extra_title %}{% endblock %}</title>
</head>

<body>
    <header class="container-fluid fixed-top">

        <!-- Homepage Logo -->
        <div id="topnav" class="row bg-white pt-lg-2 d-none d-lg-flex">
            <div class="col-12 col-lg-4 my-auto py-1 py-lg-0 text-center text-lg-left">
                <a href="{% url 'home' %}" class="nav-link main-logo-link">
                    <h2 class="logo-font text-black my-0">Granite Tap</h2>
                </a>
            </div>

            <!-- searchbar -->
            <div class="col-12 col-lg-4 my-auto py-1 py-lg-0">
                <form method="GET" action="{% url 'products' %}">
                    <div class="input-group w-100">
                        <input class="form-control border border-black rounded-0" type="text" name="q"
                            placeholder="Search our site">
                        <div class="input-group-append">
                            <button class="form-control btn btn-black border border-black rounded-0" type="submit">
                                <span class="icon">
                                    <i class="fas fa-search"></i>
                                </span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-12 col-lg-4 my-auto py-1 py-lg-0">
                <ul class="list-inline list-unstyled text-center text-lg-right my-0">
                    <!-- About Link -->
                    <li class="list-inline-item">
                        <a class="text-info text-black nav-link p-0" href="{% url 'about_page' %}">
                            <div class="text-center">
                                <div><i class="fa-solid fa-info"></i></div>
                                <p class="my-0">About</p>
                            </div>
                        </a>
                    </li>
                    <!-- My Account  -->
                    <li class="list-inline-item dropdown">
                        <a class="text-black nav-link p-0" href="#" id="user-options" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <div class="text-center">
                                <div><i class="fas fa-user fa-lg"></i></div>
                                <!-- Indicates the user is logged in -->
                                {% if request.user.is_authenticated %}
                                    <p class="my-0">{{ request.user.username }}</p>
                                {% else %}
                                    <p class="my-0">My Account</p>
                                {% endif %}
                            </div>
                        </a>
                        <div class="dropdown-menu border-0" aria-labelledby="user-options">
                            {% if request.user.is_authenticated %}
                                {% if request.user.is_superuser %}
                                    <a href="{% url 'add_product' %}" class="dropdown-item">Product Management</a>
                                {% endif %}
                                <a href="{% url 'profile' %}" class="dropdown-item">My Profile</a>
                                {% if request.user.is_authenticated %}
                                    <a href="{% url 'wishlist:wishlist' %}" class="dropdown-item">Wishlist</a>
                                {% endif %}
                                <a href="{% url 'account_logout' %}" class="dropdown-item">Logout</a>
                            {% else %}
                                <a href="{% url 'account_signup' %}" class="dropdown-item">Register</a>
                                <a href="{% url 'account_login' %}" class="dropdown-item">Login</a>
                            {% endif %}
                        </div>
                    </li>
                    <!-- Shopping Basket -->
                    <li class="list-inline-item">
                        <a class="{% if grand_total %}text-info font-weight-bold{% else %}text-black{% endif %} nav-link p-0"
                            href="{% url 'view_bag' %}">
                            <div class="text-center">
                                <div><i class="fas fa-shopping-bag fa-lg"></i></div>
                                <p class="my-0">
                                    {% if grand_total %}
                                        £{{ grand_total|floatformat:2 }}
                                    {% else %}
                                        £0.00
                                    {% endif %}
                                </p>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <!-- Sub Menus -->
        <div class="row bg-white">
            <nav class="navbar navbar-expand-lg navbar-light w-100">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav"
                    aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                {% include 'includes/mobile-top-header.html' %}
                {% include 'includes/main-nav.html' %}
            </nav>
        </div>

        <!-- Delivery Banner -->
        <div id="delivery-banner" class="row text-center bg-black">
            <div class="col bg-black text-white">
                <h4 class="logo-font my-1 delivery-text">Free delivery on orders over £{{ free_delivery_threshold }}!</h4>
            </div>
        </div>
    </header>

    {% if messages %}
        <div class="message-container">
            {% for message in messages %}
                {% with message.level as level %}
                    {% if level == 40 %}
                        {% include 'includes/toasts/toast_error.html' %}
                    {% elif level == 30 %}
                        {% include 'includes/toasts/toast_warning.html' %}
                    {% elif level == 25 %}
                        {% include 'includes/toasts/toast_success.html' %}
                    {% else %}
                        {% include 'includes/toasts/toast_info.html' %}
                    {% endif %}
                {% endwith %}
            {% endfor %}
        </div>
    {% endif %}

    {% block page_header %}
    {% endblock %}
    
    
    {% block content %}
    {% endblock %}

    <!-- Footer -->
    <footer class="container-fluid bg-black text-white mt-5 py-3">
        <div class="row">
            <div class="col text-center">
                <p class="mb-0">
                    <a href="{% url 'about_page' %}#contact" class="text-white">Contact Us</a> |
                    <a href="{% url 'about_page' %}#newsletter" class="text-white">Subscribe to our Newsletter</a> |
                    <a href="https://www.facebook.com/login" class="text-white" target="_blank" rel="noopener" 
                        aria-label="Visit our Facebook Page (opens in a new tab)">
                        <i class="fa-brands fa-facebook"></i> Visit us on Facebook
                    </a> |
                    <a href="https://www.termsfeed.com/live/6ce57fb3-3e55-4587-9ed0-703fd41df7f0" class="text-white" target="_blank" rel="noopener"
                        aria-label="Click here to view our privacy policy(opens in a new tab)">Privacy Policy</a>
                </p>
            </div>
        </div>
    </footer>

    {% block postloadjs %}
        <script type="text/javascript">
            $('.toast').toast('show');
        </script>
    {% endblock %}


</body>

</html>